In [1]:
from constant_iv_term_structure_engine import constantIVTermStructureEngine
import polars as pl

engine = constantIVTermStructureEngine(ticker="LITE", auto_sync=False)

# Step 1: Fetch equity data
equity_df = engine._fetch_equity_data()

# Step 2: Fetch options data
options_df = engine._fetch_options_data()

In [2]:
# Step 3: Filter options
filtered_options_df = engine._filter_options(options_df)

# Step 4: Add rolling equity metrics
equity_df = engine._add_equity_rolling_metrics(equity_df)

# Step 5: Filter equity
filtered_equity_df = engine._filter_equity(equity_df)

# Step 6: Add ATM diff, ATM IV, days_to_expiry: MIGHT BE THIS ONE
filtered_options_df = engine._add_options_derived_columns(filtered_options_df)

# # Step 7: Constant-maturity IV interpolation
cm_df = engine._compute_constant_maturity_iv(filtered_options_df)

# Step 8: Join options with constant-maturity data
options_cm_df = engine._join_options_with_cm(filtered_options_df, cm_df)

# Step 9: Join with equity data
consolidated_df = engine._join_with_equity(options_cm_df, filtered_equity_df)

In [3]:
# Step 10: Compute derived columns (SLOPE, IVRV_SLOPE, straddle prices)
consolidated_df1 = engine._compute_derived_columns(consolidated_df)

# Step 11: Final selection + wret
result = engine._select_final_and_compute_wret(consolidated_df1)

# Step 12: Add quantile ranking
result = engine.add_ntile(result, col=engine.rank_column, n=engine.n_tiles, by="trade_date")

In [6]:
result.filter(pl.col("cOpra") == "LITE260313C00667500")

shape: (1, 30)
┌────────┬──────────────┬────────────┬─────────────┬───┬────────────┬─────────────┬──────┬─────────┐
│ ticker ┆ expirDate    ┆ trade_date ┆ cOpra       ┆ … ┆ spread_abs ┆ spread_pct_ ┆ wret ┆ q_slope │
│ ---    ┆ ---          ┆ ---        ┆ ---         ┆   ┆ ---        ┆ mid         ┆ ---  ┆ ---     │
│ str    ┆ datetime[μs] ┆ date       ┆ str         ┆   ┆ f64        ┆ ---         ┆ f64  ┆ i32     │
│        ┆              ┆            ┆             ┆   ┆            ┆ f64         ┆      ┆         │
╞════════╪══════════════╪════════════╪═════════════╪═══╪════════════╪═════════════╪══════╪═════════╡
│ LITE   ┆ 2026-03-13   ┆ 2026-03-11 ┆ LITE260313C ┆ … ┆ 10.0       ┆ 0.206186    ┆ null ┆ 10      │
│        ┆ 00:00:00     ┆            ┆ 00667500    ┆   ┆            ┆             ┆      ┆         │
└────────┴──────────────┴────────────┴─────────────┴───┴────────────┴─────────────┴──────┴─────────┘

In [5]:
result.filter(pl.col("trade_date") == pl.col("trade_date").max())

shape: (1, 30)
┌────────┬──────────────┬────────────┬─────────────┬───┬────────────┬─────────────┬──────┬─────────┐
│ ticker ┆ expirDate    ┆ trade_date ┆ cOpra       ┆ … ┆ spread_abs ┆ spread_pct_ ┆ wret ┆ q_slope │
│ ---    ┆ ---          ┆ ---        ┆ ---         ┆   ┆ ---        ┆ mid         ┆ ---  ┆ ---     │
│ str    ┆ datetime[μs] ┆ date       ┆ str         ┆   ┆ f64        ┆ ---         ┆ f64  ┆ i32     │
│        ┆              ┆            ┆             ┆   ┆            ┆ f64         ┆      ┆         │
╞════════╪══════════════╪════════════╪═════════════╪═══╪════════════╪═════════════╪══════╪═════════╡
│ LITE   ┆ 2026-03-13   ┆ 2026-03-11 ┆ LITE260313C ┆ … ┆ 10.0       ┆ 0.206186    ┆ null ┆ 10      │
│        ┆ 00:00:00     ┆            ┆ 00667500    ┆   ┆            ┆             ┆      ┆         │
└────────┴──────────────┴────────────┴─────────────┴───┴────────────┴─────────────┴──────┴─────────┘